name: Prepare next release ğŸš€

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Run release draft to extract labels â˜•ï¸
    runs-on: ubuntu-latest
    steps:
      - name: Run release draft to extract labels â˜•ï¸
        uses: tchoupinax/repo-config/shared-actions/dx/prepare-draft-release@a31e30afc835847e45f0ea86211a337cddd3b723
        with:
          appId: ${{ secrets.DEPLOY_APP_ID }}
          privateKey: ${{ secrets.DEPLOY_APP_KEY }}
