name: Pull request checks ğŸ”

on:
  pull_request:

jobs:
  lint:
    name: Check code quality ğŸ«†
    runs-on: ubuntu-latest
    steps:
      - name: Check code quality ğŸ«†
        uses: tchoupinax/repo-config/shared-actions/steps/golang/golangci@v0.1.1

  build:
    name: Check build success ğŸ¦«
    runs-on: ubuntu-latest
    steps:
      - name: Check build success ğŸ¦«
        uses: tchoupinax/repo-config/shared-actions/steps/golang/goreleaser-build-only@v0.1.1

  labels:
    name: Autodetect labels2 ğŸ” 
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.DEPLOY_APP_ID }}
          private-key: ${{ secrets.DEPLOY_APP_KEY }}

      - name: labels
        uses: fuxingloh/multi-labeler@v4
        with:
          github-token: ${{ steps.app-token.outputs.token }}